# Generated by Django 3.0.3 on 2020-02-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('H', 'HOUSE'), ('A', 'APARTMENT')], default='H', max_length=1),
            preserve_default=False,
        ),
    ]
